
// Generated by Cadence Genus(TM) Synthesis Solution 16.10-p006_1
// Generated on: Jun 21 2017 18:07:51

// Verification Directory fv/TF 

module TF(A, B, C, D, F);
  input A, B, C, D;
  output F;
  wire A, B, C, D;
  wire F;
  wire not_a, not_b, not_c, not_d, not_f;
  inv inv1(.A (A), .Z (not_a));
  inv inv2(.A (B), .Z (not_b));
  inv inv3(.A (C), .Z (not_c));
  inv inv4(.A (D), .Z (not_d));
  inv inv5(.A (not_f), .Z (F));
  Complex_f2 mx(.A (not_a), .B (not_b), .C (not_c), .D (not_d), .S
       (not_f));
endmodule

