# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.8.7"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false
  
  (1..4).each do |i|
    config.vm.define "client#{i}" do |vb|
	  vb.vm.network "forwarded_port", id: "ssh", guest: "22", host: "220#{i}"
      config.vm.provider "virtualbox" do |vb|
        vb.name = "client#{i}"
        vb.memory = "512"
        vb.cpus = 1
      end
      vb.vm.hostname = "client#{i}"
      vb.vm.network "private_network", ip: "192.168.255.#{i}"
      if i > 1
	    vb.vm.provision "shell", inline: <<-SLAVE
		  apt-get -q update
		  apt-get -qyf install tmux git
		  apt-get -qy autoremove
		  apt-get -q clean
		SLAVE
	  else
        vb.vm.provision "shell", inline: <<-MASTER
          apt-get -q update
          apt-get -qyf install tmux git fping gedit
          apt-get -qy autoremove
          apt-get -q clean
        MASTER
      end
	  vb.vm.provision "shell", inline: "git clone https://github.com/mebuffet/PPD", privileged: false
	  vb.vm.provision "shell", inline: "git config --global user.email mebuffet@gmail.com", privileged: false
	  vb.vm.provision "shell", inline: "git config --global user.name Maiki", privileged: false
	  vb.vm.provision "shell", inline: "git config --global push.default simple", privileged: false
	end
  end
end
