/*
###############################################################
#  Generated by:      Cadence Innovus 16.10-p004_1
#  OS:                Linux x86_64(Host ID kriti)
#  Generated on:      Tue Nov 28 12:36:09 2017
#  Design:            PIF2WB
#  Command:           write_netlist /home/vlsi2_g05/VLSI2/pif2wb/src/PIF2WB.pos_physical/PIF2WB.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 16.10-p006_1
// Generated on: Nov 28 2017 01:05:00
// Verification Directory fv/PIF2WB 
module PIF2WB (
	CLK, 
	RST, 
	PIReqVALID, 
	PIReqCNTL, 
	PIReqADRS, 
	PIReqDATA, 
	PIReqDataBE, 
	POReqRDY, 
	PORespVALID, 
	PORespCNTL, 
	PORespDATA, 
	PIRespRDY, 
	ACK_I, 
	DAT_I, 
	ERR_I, 
	ADR_O, 
	DAT_O, 
	CYC_O, 
	SEL_O, 
	STB_O, 
	WE_O, 
	BTE_O, 
	CTI_O);
   input CLK;
   input RST;
   input PIReqVALID;
   input [7:0] PIReqCNTL;
   input [31:0] PIReqADRS;
   input [31:0] PIReqDATA;
   input [3:0] PIReqDataBE;
   output POReqRDY;
   output PORespVALID;
   output [7:0] PORespCNTL;
   output [31:0] PORespDATA;
   input PIRespRDY;
   input ACK_I;
   input [31:0] DAT_I;
   input ERR_I;
   output [31:0] ADR_O;
   output [31:0] DAT_O;
   output CYC_O;
   output [3:0] SEL_O;
   output STB_O;
   output WE_O;
   output [1:0] BTE_O;
   output [2:0] CTI_O;

   // Internal wires
   wire FE_OFN8_n_96;
   wire FE_OFN7_n_94;
   wire FE_RN_1;
   wire FE_OFN5_n_97;
   wire FE_OFN4_n_97;
   wire FE_OFN3_n_88;
   wire FE_OFN2_FE_OFN0_n_172;
   wire FE_OFN1_FE_OFN0_n_172;
   wire FE_OFN0_n_172;
   wire FE_DBTN0_n_88;
   wire [2:0] state;
   wire [3:0] TOT_TRANSFER_I;
   wire [31:0] Counter_Burst_Transfer_plus_69_28;
   wire Counter_Burst_Transfer_add_69_28_n_635;
   wire Counter_Burst_Transfer_add_69_28_n_637;
   wire Counter_Burst_Transfer_add_69_28_n_639;
   wire Counter_Burst_Transfer_add_69_28_n_641;
   wire Counter_Burst_Transfer_add_69_28_n_643;
   wire Counter_Burst_Transfer_add_69_28_n_645;
   wire Counter_Burst_Transfer_add_69_28_n_647;
   wire Counter_Burst_Transfer_add_69_28_n_649;
   wire Counter_Burst_Transfer_add_69_28_n_651;
   wire Counter_Burst_Transfer_add_69_28_n_653;
   wire Counter_Burst_Transfer_add_69_28_n_655;
   wire Counter_Burst_Transfer_add_69_28_n_657;
   wire Counter_Burst_Transfer_add_69_28_n_659;
   wire Counter_Burst_Transfer_add_69_28_n_661;
   wire Counter_Burst_Transfer_add_69_28_n_663;
   wire Counter_Burst_Transfer_add_69_28_n_665;
   wire Counter_Burst_Transfer_add_69_28_n_667;
   wire Counter_Burst_Transfer_add_69_28_n_669;
   wire Counter_Burst_Transfer_add_69_28_n_671;
   wire Counter_Burst_Transfer_add_69_28_n_673;
   wire Counter_Burst_Transfer_add_69_28_n_675;
   wire Counter_Burst_Transfer_add_69_28_n_677;
   wire Counter_Burst_Transfer_add_69_28_n_679;
   wire Counter_Burst_Transfer_add_69_28_n_681;
   wire Counter_Burst_Transfer_add_69_28_n_683;
   wire Counter_Burst_Transfer_add_69_28_n_685;
   wire Counter_Burst_Transfer_add_69_28_n_687;
   wire Counter_Burst_Transfer_add_69_28_n_689;
   wire \N_TRANSFER[0] ;
   wire \N_TRANSFER[1] ;
   wire \N_TRANSFER[2] ;
   wire \N_TRANSFER[3] ;
   wire \TOT_TRANSFER_O[0] ;
   wire \TOT_TRANSFER_O[1] ;
   wire \TOT_TRANSFER_O[2] ;
   wire \TOT_TRANSFER_O[3] ;
   wire n_4;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_135;
   wire n_136;
   wire n_169;
   wire n_170;
   wire n_171;
   wire n_172;
   wire n_315;

   assign CTI_O[0] = CTI_O[2] ;
   assign BTE_O[0] = 1'b0 ;
   assign BTE_O[1] = 1'b0 ;
   assign PORespCNTL[1] = ERR_I ;
   assign PORespCNTL[2] = ERR_I ;
   assign PORespCNTL[3] = 1'b0 ;
   assign PORespCNTL[4] = 1'b0 ;
   assign PORespCNTL[5] = 1'b0 ;
   assign PORespCNTL[6] = 1'b0 ;
   assign PORespCNTL[7] = 1'b0 ;
   assign PORespVALID = ACK_I ;
   assign POReqRDY = 1'b1 ;

   HS65_GS_BFX27 FE_OFC8_n_96 (.A(n_96),
	.Z(FE_OFN8_n_96));
   HS65_GS_BFX27 FE_OFC7_n_94 (.A(n_94),
	.Z(FE_OFN7_n_94));
   HS65_GS_BFX27 FE_OFC6_STB_O (.A(FE_RN_1),
	.Z(STB_O));
   HS65_GS_BFX27 FE_OFC5_n_97 (.A(n_97),
	.Z(FE_OFN5_n_97));
   HS65_GS_BFX27 FE_OFC4_n_97 (.A(n_97),
	.Z(FE_OFN4_n_97));
   HS65_GS_BFX27 FE_OFC3_n_88 (.A(n_88),
	.Z(FE_OFN3_n_88));
   HS65_GS_BFX27 FE_OFC2_FE_OFN0_n_172 (.A(FE_OFN0_n_172),
	.Z(FE_OFN2_FE_OFN0_n_172));
   HS65_GS_BFX27 FE_OFC1_FE_OFN0_n_172 (.A(FE_OFN0_n_172),
	.Z(FE_OFN1_FE_OFN0_n_172));
   HS65_GS_BFX27 FE_OFC0_n_172 (.A(n_172),
	.Z(FE_OFN0_n_172));
   HS65_GS_IVX9 FE_DBTC0_n_88 (.A(n_88),
	.Z(FE_DBTN0_n_88));
   HS65_GS_IVX9 g939_730256179 (.A(RST),
	.Z(n_97));
   HS65_GS_NAND2AX4 g1397_730256179 (.A(CTI_O[2]),
	.B(n_92),
	.Z(PORespCNTL[0]));
   HS65_GS_BTHX10 g205_730256179 (.A(PIReqDATA[22]),
	.E(n_96),
	.Z(DAT_O[22]));
   HS65_GS_BTHX10 g206_730256179 (.A(PIReqDATA[21]),
	.E(n_96),
	.Z(DAT_O[21]));
   HS65_GS_BTHX10 g207_730256179 (.A(PIReqDATA[20]),
	.E(n_96),
	.Z(DAT_O[20]));
   HS65_GS_BTHX10 g208_730256179 (.A(PIReqDATA[19]),
	.E(n_96),
	.Z(DAT_O[19]));
   HS65_GS_BTHX10 g209_730256179 (.A(PIReqDATA[18]),
	.E(n_96),
	.Z(DAT_O[18]));
   HS65_GS_BTHX10 g210_730256179 (.A(PIReqDATA[17]),
	.E(FE_OFN8_n_96),
	.Z(DAT_O[17]));
   HS65_GS_BTHX10 g211_730256179 (.A(PIReqDATA[16]),
	.E(FE_OFN8_n_96),
	.Z(DAT_O[16]));
   HS65_GS_BTHX10 g212_730256179 (.A(PIReqDATA[15]),
	.E(FE_OFN8_n_96),
	.Z(DAT_O[15]));
   HS65_GS_BTHX10 g190_730256179 (.A(PIReqDATA[14]),
	.E(FE_OFN8_n_96),
	.Z(DAT_O[14]));
   HS65_GS_BTHX10 g191_730256179 (.A(PIReqDATA[13]),
	.E(FE_OFN8_n_96),
	.Z(DAT_O[13]));
   HS65_GS_BTHX10 g193_730256179 (.A(PIReqDATA[12]),
	.E(FE_OFN8_n_96),
	.Z(DAT_O[12]));
   HS65_GS_BTHX10 g194_730256179 (.A(PIReqDATA[11]),
	.E(FE_OFN8_n_96),
	.Z(DAT_O[11]));
   HS65_GS_BTHX10 g195_730256179 (.A(PIReqDATA[10]),
	.E(FE_OFN8_n_96),
	.Z(DAT_O[10]));
   HS65_GS_BTHX10 g196_730256179 (.A(PIReqDATA[9]),
	.E(FE_OFN8_n_96),
	.Z(DAT_O[9]));
   HS65_GS_BTHX10 g197_730256179 (.A(PIReqDATA[8]),
	.E(FE_OFN8_n_96),
	.Z(DAT_O[8]));
   HS65_GS_BTHX10 g213_730256179 (.A(PIReqDATA[7]),
	.E(FE_OFN8_n_96),
	.Z(DAT_O[7]));
   HS65_GS_BTHX10 g199_730256179 (.A(PIReqDATA[6]),
	.E(FE_OFN8_n_96),
	.Z(DAT_O[6]));
   HS65_GS_BTHX10 g181_730256179 (.A(PIReqDATA[28]),
	.E(FE_OFN8_n_96),
	.Z(DAT_O[28]));
   HS65_GS_BTHX10 g201_730256179 (.A(PIReqDATA[4]),
	.E(FE_OFN8_n_96),
	.Z(DAT_O[4]));
   HS65_GS_BTHX10 g202_730256179 (.A(PIReqDATA[3]),
	.E(FE_OFN8_n_96),
	.Z(DAT_O[3]));
   HS65_GS_BTHX10 g214_730256179 (.A(PIReqDATA[2]),
	.E(FE_OFN8_n_96),
	.Z(DAT_O[2]));
   HS65_GS_BTHX10 g215_730256179 (.A(PIReqDATA[1]),
	.E(n_96),
	.Z(DAT_O[1]));
   HS65_GS_BTHX10 g216_730256179 (.A(PIReqDATA[0]),
	.E(n_96),
	.Z(DAT_O[0]));
   HS65_GS_BTHX10 g203_730256179 (.A(PIReqDATA[31]),
	.E(n_96),
	.Z(DAT_O[31]));
   HS65_GS_BTHX10 g176_730256179 (.A(PIReqDATA[30]),
	.E(n_96),
	.Z(DAT_O[30]));
   HS65_GS_BTHX10 g179_730256179 (.A(PIReqDATA[29]),
	.E(n_96),
	.Z(DAT_O[29]));
   HS65_GS_BTHX10 g200_730256179 (.A(PIReqDATA[5]),
	.E(FE_OFN8_n_96),
	.Z(DAT_O[5]));
   HS65_GS_BTHX10 g182_730256179 (.A(PIReqDATA[27]),
	.E(FE_OFN8_n_96),
	.Z(DAT_O[27]));
   HS65_GS_BTHX10 g187_730256179 (.A(PIReqDATA[26]),
	.E(n_96),
	.Z(DAT_O[26]));
   HS65_GS_BTHX10 g188_730256179 (.A(PIReqDATA[25]),
	.E(FE_OFN8_n_96),
	.Z(DAT_O[25]));
   HS65_GS_BTHX10 g189_730256179 (.A(PIReqDATA[24]),
	.E(FE_OFN8_n_96),
	.Z(DAT_O[24]));
   HS65_GS_BTHX10 g204_730256179 (.A(PIReqDATA[23]),
	.E(n_96),
	.Z(DAT_O[23]));
   HS65_GS_MUX21I1X3 g1398_730256179 (.D0(FE_OFN0_n_172),
	.D1(n_315),
	.S0(n_91),
	.Z(CYC_O));
   HS65_GS_MUX21X4 g1399_730256179 (.D0(n_90),
	.D1(n_315),
	.S0(n_136),
	.Z(WE_O));
   HS65_GS_NOR2X2 g1400_730256179 (.A(n_95),
	.B(n_315),
	.Z(CTI_O[2]));
   HS65_GS_AND3ABCX9 g1401_730256179 (.A(n_169),
	.B(FE_OFN0_n_172),
	.C(n_93),
	.Z(n_96));
   HS65_GS_NOR3X1 g1402_730256179 (.A(n_135),
	.B(n_136),
	.C(n_93),
	.Z(n_95));
   HS65_GS_BTHX10 g230_730256179 (.A(DAT_I[20]),
	.E(n_94),
	.Z(PORespDATA[20]));
   HS65_GS_BTHX10 g229_730256179 (.A(DAT_I[21]),
	.E(n_94),
	.Z(PORespDATA[21]));
   HS65_GS_BTHX10 g231_730256179 (.A(DAT_I[19]),
	.E(n_94),
	.Z(PORespDATA[19]));
   HS65_GS_BTHX10 g232_730256179 (.A(DAT_I[18]),
	.E(n_94),
	.Z(PORespDATA[18]));
   HS65_GS_BTHX10 g233_730256179 (.A(DAT_I[17]),
	.E(FE_OFN7_n_94),
	.Z(PORespDATA[17]));
   HS65_GS_BTHX10 g234_730256179 (.A(DAT_I[16]),
	.E(FE_OFN7_n_94),
	.Z(PORespDATA[16]));
   HS65_GS_BTHX10 g235_730256179 (.A(DAT_I[15]),
	.E(FE_OFN7_n_94),
	.Z(PORespDATA[15]));
   HS65_GS_BTHX10 g236_730256179 (.A(DAT_I[14]),
	.E(FE_OFN7_n_94),
	.Z(PORespDATA[14]));
   HS65_GS_BTHX10 g217_730256179 (.A(DAT_I[31]),
	.E(FE_OFN7_n_94),
	.Z(PORespDATA[31]));
   HS65_GS_BTHX10 g237_730256179 (.A(DAT_I[13]),
	.E(FE_OFN7_n_94),
	.Z(PORespDATA[13]));
   HS65_GS_BTHX10 g238_730256179 (.A(DAT_I[12]),
	.E(FE_OFN7_n_94),
	.Z(PORespDATA[12]));
   HS65_GS_BTHX10 g239_730256179 (.A(DAT_I[11]),
	.E(FE_OFN7_n_94),
	.Z(PORespDATA[11]));
   HS65_GS_BTHX10 g240_730256179 (.A(DAT_I[10]),
	.E(FE_OFN7_n_94),
	.Z(PORespDATA[10]));
   HS65_GS_BTHX10 g220_730256179 (.A(DAT_I[30]),
	.E(FE_OFN7_n_94),
	.Z(PORespDATA[30]));
   HS65_GS_BTHX10 g242_730256179 (.A(DAT_I[8]),
	.E(FE_OFN7_n_94),
	.Z(PORespDATA[8]));
   HS65_GS_BTHX10 g241_730256179 (.A(DAT_I[9]),
	.E(FE_OFN7_n_94),
	.Z(PORespDATA[9]));
   HS65_GS_BTHX10 g243_730256179 (.A(DAT_I[7]),
	.E(FE_OFN7_n_94),
	.Z(PORespDATA[7]));
   HS65_GS_BTHX10 g244_730256179 (.A(DAT_I[6]),
	.E(FE_OFN7_n_94),
	.Z(PORespDATA[6]));
   HS65_GS_BTHX10 g245_730256179 (.A(DAT_I[5]),
	.E(FE_OFN7_n_94),
	.Z(PORespDATA[5]));
   HS65_GS_BTHX10 g246_730256179 (.A(DAT_I[4]),
	.E(FE_OFN7_n_94),
	.Z(PORespDATA[4]));
   HS65_GS_BTHX10 g247_730256179 (.A(DAT_I[3]),
	.E(FE_OFN7_n_94),
	.Z(PORespDATA[3]));
   HS65_GS_BTHX10 g248_730256179 (.A(DAT_I[2]),
	.E(FE_OFN7_n_94),
	.Z(PORespDATA[2]));
   HS65_GS_BTHX10 g221_730256179 (.A(DAT_I[29]),
	.E(n_94),
	.Z(PORespDATA[29]));
   HS65_GS_BTHX10 g249_730256179 (.A(DAT_I[1]),
	.E(FE_OFN7_n_94),
	.Z(PORespDATA[1]));
   HS65_GS_BTHX10 g250_730256179 (.A(DAT_I[0]),
	.E(FE_OFN7_n_94),
	.Z(PORespDATA[0]));
   HS65_GS_BTHX10 g222_730256179 (.A(DAT_I[28]),
	.E(n_94),
	.Z(PORespDATA[28]));
   HS65_GS_BTHX10 g224_730256179 (.A(DAT_I[26]),
	.E(n_94),
	.Z(PORespDATA[26]));
   HS65_GS_BTHX10 g223_730256179 (.A(DAT_I[27]),
	.E(n_94),
	.Z(PORespDATA[27]));
   HS65_GS_BTHX10 g225_730256179 (.A(DAT_I[25]),
	.E(n_94),
	.Z(PORespDATA[25]));
   HS65_GS_BTHX10 g226_730256179 (.A(DAT_I[24]),
	.E(n_94),
	.Z(PORespDATA[24]));
   HS65_GS_BTHX10 g227_730256179 (.A(DAT_I[23]),
	.E(n_94),
	.Z(PORespDATA[23]));
   HS65_GS_BTHX10 g228_730256179 (.A(DAT_I[22]),
	.E(n_94),
	.Z(PORespDATA[22]));
   HS65_GS_NOR2AX3 g1403_730256179 (.A(n_92),
	.B(FE_OFN0_n_172),
	.Z(CTI_O[1]));
   HS65_GS_NAND4ABX3 g1404_730256179 (.A(n_85),
	.B(n_87),
	.C(n_86),
	.D(n_84),
	.Z(n_315));
   HS65_GS_NOR2X6 g1405_730256179 (.A(n_88),
	.B(FE_OFN2_FE_OFN0_n_172),
	.Z(FE_RN_1));
   HS65_GS_NOR2X9 g1406_730256179 (.A(n_90),
	.B(FE_OFN0_n_172),
	.Z(n_94));
   HS65_GS_OR2X4 g1407_730256179 (.A(n_171),
	.B(n_170),
	.Z(n_93));
   HS65_GS_AOI21X2 g1408_730256179 (.A(state[1]),
	.B(state[0]),
	.C(n_169),
	.Z(n_92));
   HS65_GS_AOI21X2 g1409_730256179 (.A(n_136),
	.B(n_171),
	.C(FE_DBTN0_n_88),
	.Z(n_91));
   HS65_GS_NOR2X2 g1412_730256179 (.A(n_83),
	.B(n_82),
	.Z(n_90));
   HS65_GS_AND2X4 g1413_730256179 (.A(n_83),
	.B(state[1]),
	.Z(n_170));
   HS65_GS_NOR2AX6 g1414_730256179 (.A(state[2]),
	.B(n_81),
	.Z(n_88));
   HS65_GS_NOR2AX3 g1415_730256179 (.A(n_82),
	.B(state[2]),
	.Z(n_169));
   HS65_GS_NOR2AX3 g1416_730256179 (.A(n_81),
	.B(state[2]),
	.Z(n_172));
   HS65_GSS_XOR2X6 g1417_730256179 (.A(\TOT_TRANSFER_O[0] ),
	.B(\N_TRANSFER[0] ),
	.Z(n_87));
   HS65_GSS_XNOR2X6 g1418_730256179 (.A(\N_TRANSFER[2] ),
	.B(\TOT_TRANSFER_O[2] ),
	.Z(n_86));
   HS65_GSS_XOR2X6 g1419_730256179 (.A(\TOT_TRANSFER_O[1] ),
	.B(\N_TRANSFER[1] ),
	.Z(n_85));
   HS65_GSS_XNOR2X6 g1420_730256179 (.A(\N_TRANSFER[3] ),
	.B(\TOT_TRANSFER_O[3] ),
	.Z(n_84));
   HS65_GS_AND2X4 g1421_730256179 (.A(n_81),
	.B(state[2]),
	.Z(n_135));
   HS65_GS_NOR2X6 g1422_730256179 (.A(state[0]),
	.B(state[2]),
	.Z(n_83));
   HS65_GS_NOR2AX3 g1423_730256179 (.A(state[0]),
	.B(state[1]),
	.Z(n_82));
   HS65_GS_NOR2X6 g1424_730256179 (.A(state[0]),
	.B(state[1]),
	.Z(n_81));
   HS65_GS_AND2X4 g1425_730256179 (.A(state[2]),
	.B(state[0]),
	.Z(n_171));
   HS65_GS_AND2X4 g1426_730256179 (.A(state[2]),
	.B(state[1]),
	.Z(n_136));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[0]  (.CP(CLK),
	.D(n_53),
	.Q(ADR_O[0]),
	.RN(FE_OFN5_n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[1]  (.CP(CLK),
	.D(n_54),
	.Q(ADR_O[1]),
	.RN(FE_OFN5_n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[2]  (.CP(CLK),
	.D(n_48),
	.Q(ADR_O[2]),
	.RN(FE_OFN5_n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[3]  (.CP(CLK),
	.D(n_45),
	.Q(ADR_O[3]),
	.RN(FE_OFN5_n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[4]  (.CP(CLK),
	.D(n_41),
	.Q(ADR_O[4]),
	.RN(FE_OFN5_n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[5]  (.CP(CLK),
	.D(n_37),
	.Q(ADR_O[5]),
	.RN(FE_OFN5_n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[6]  (.CP(CLK),
	.D(n_38),
	.Q(ADR_O[6]),
	.RN(FE_OFN5_n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[7]  (.CP(CLK),
	.D(n_36),
	.Q(ADR_O[7]),
	.RN(FE_OFN5_n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[8]  (.CP(CLK),
	.D(n_35),
	.Q(ADR_O[8]),
	.RN(FE_OFN5_n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[9]  (.CP(CLK),
	.D(n_34),
	.Q(ADR_O[9]),
	.RN(FE_OFN5_n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[10]  (.CP(CLK),
	.D(n_33),
	.Q(ADR_O[10]),
	.RN(FE_OFN5_n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[11]  (.CP(CLK),
	.D(n_31),
	.Q(ADR_O[11]),
	.RN(FE_OFN5_n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[12]  (.CP(CLK),
	.D(n_30),
	.Q(ADR_O[12]),
	.RN(FE_OFN5_n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[13]  (.CP(CLK),
	.D(n_29),
	.Q(ADR_O[13]),
	.RN(FE_OFN4_n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[14]  (.CP(CLK),
	.D(n_28),
	.Q(ADR_O[14]),
	.RN(FE_OFN4_n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[15]  (.CP(CLK),
	.D(n_27),
	.Q(ADR_O[15]),
	.RN(FE_OFN4_n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[16]  (.CP(CLK),
	.D(n_26),
	.Q(ADR_O[16]),
	.RN(FE_OFN4_n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[17]  (.CP(CLK),
	.D(n_25),
	.Q(ADR_O[17]),
	.RN(FE_OFN5_n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[18]  (.CP(CLK),
	.D(n_24),
	.Q(ADR_O[18]),
	.RN(FE_OFN5_n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[19]  (.CP(CLK),
	.D(n_23),
	.Q(ADR_O[19]),
	.RN(FE_OFN5_n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[20]  (.CP(CLK),
	.D(n_32),
	.Q(ADR_O[20]),
	.RN(n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[21]  (.CP(CLK),
	.D(n_52),
	.Q(ADR_O[21]),
	.RN(n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[22]  (.CP(CLK),
	.D(n_51),
	.Q(ADR_O[22]),
	.RN(n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[23]  (.CP(CLK),
	.D(n_50),
	.Q(ADR_O[23]),
	.RN(FE_OFN4_n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[24]  (.CP(CLK),
	.D(n_49),
	.Q(ADR_O[24]),
	.RN(FE_OFN4_n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[25]  (.CP(CLK),
	.D(n_47),
	.Q(ADR_O[25]),
	.RN(FE_OFN4_n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[26]  (.CP(CLK),
	.D(n_46),
	.Q(ADR_O[26]),
	.RN(FE_OFN4_n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[27]  (.CP(CLK),
	.D(n_44),
	.Q(ADR_O[27]),
	.RN(FE_OFN4_n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[28]  (.CP(CLK),
	.D(n_56),
	.Q(ADR_O[28]),
	.RN(FE_OFN4_n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[29]  (.CP(CLK),
	.D(n_55),
	.Q(ADR_O[29]),
	.RN(FE_OFN4_n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[30]  (.CP(CLK),
	.D(n_40),
	.Q(ADR_O[30]),
	.RN(FE_OFN4_n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_ADR_REG_reg[31]  (.CP(CLK),
	.D(n_39),
	.Q(ADR_O[31]),
	.RN(FE_OFN4_n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_N_reg[0]  (.CP(CLK),
	.D(n_43),
	.Q(\N_TRANSFER[0] ),
	.RN(FE_OFN4_n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_N_reg[1]  (.CP(CLK),
	.D(n_66),
	.Q(\N_TRANSFER[1] ),
	.RN(n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_N_reg[2]  (.CP(CLK),
	.D(n_74),
	.Q(\N_TRANSFER[2] ),
	.RN(FE_OFN4_n_97));
   HS65_GS_DFPRQX9 \Counter_Burst_Transfer_N_reg[3]  (.CP(CLK),
	.D(n_76),
	.Q(\N_TRANSFER[3] ),
	.RN(FE_OFN4_n_97));
   HS65_GS_LDHQX9 \TOT_TRANSFER_I_reg[1]  (.D(n_18),
	.G(FE_OFN2_FE_OFN0_n_172),
	.Q(TOT_TRANSFER_I[1]));
   HS65_GS_LDHQX9 \TOT_TRANSFER_I_reg[2]  (.D(PIReqCNTL[2]),
	.G(FE_OFN2_FE_OFN0_n_172),
	.Q(TOT_TRANSFER_I[2]));
   HS65_GS_LDHQX9 \TOT_TRANSFER_I_reg[3]  (.D(n_8),
	.G(FE_OFN2_FE_OFN0_n_172),
	.Q(TOT_TRANSFER_I[3]));
   HS65_GS_SDFPRQX9 \reg0_temp_reg[0]  (.CP(CLK),
	.D(SEL_O[0]),
	.Q(SEL_O[0]),
	.RN(FE_OFN5_n_97),
	.TE(FE_OFN0_n_172),
	.TI(PIReqDataBE[0]));
   HS65_GS_SDFPRQX9 \reg0_temp_reg[1]  (.CP(CLK),
	.D(SEL_O[1]),
	.Q(SEL_O[1]),
	.RN(FE_OFN5_n_97),
	.TE(FE_OFN0_n_172),
	.TI(PIReqDataBE[1]));
   HS65_GS_SDFPRQX9 \reg0_temp_reg[2]  (.CP(CLK),
	.D(SEL_O[2]),
	.Q(SEL_O[2]),
	.RN(n_97),
	.TE(FE_OFN0_n_172),
	.TI(PIReqDataBE[2]));
   HS65_GS_SDFPRQX9 \reg0_temp_reg[3]  (.CP(CLK),
	.D(SEL_O[3]),
	.Q(SEL_O[3]),
	.RN(FE_OFN4_n_97),
	.TE(FE_OFN2_FE_OFN0_n_172),
	.TI(PIReqDataBE[3]));
   HS65_GS_DFPRQX9 \reg1_temp_reg[0]  (.CP(CLK),
	.D(n_16),
	.Q(\TOT_TRANSFER_O[0] ),
	.RN(FE_OFN4_n_97));
   HS65_GS_SDFPRQX9 \reg1_temp_reg[1]  (.CP(CLK),
	.D(\TOT_TRANSFER_O[1] ),
	.Q(\TOT_TRANSFER_O[1] ),
	.RN(FE_OFN4_n_97),
	.TE(FE_OFN2_FE_OFN0_n_172),
	.TI(TOT_TRANSFER_I[1]));
   HS65_GS_SDFPRQX9 \reg1_temp_reg[2]  (.CP(CLK),
	.D(\TOT_TRANSFER_O[2] ),
	.Q(\TOT_TRANSFER_O[2] ),
	.RN(n_97),
	.TE(FE_OFN2_FE_OFN0_n_172),
	.TI(TOT_TRANSFER_I[2]));
   HS65_GS_SDFPRQX9 \reg1_temp_reg[3]  (.CP(CLK),
	.D(\TOT_TRANSFER_O[3] ),
	.Q(\TOT_TRANSFER_O[3] ),
	.RN(n_97),
	.TE(FE_OFN2_FE_OFN0_n_172),
	.TI(TOT_TRANSFER_I[3]));
   HS65_GS_DFPRQX9 \state_reg[0]  (.CP(CLK),
	.D(n_69),
	.Q(state[0]),
	.RN(FE_OFN5_n_97));
   HS65_GS_DFPRQX9 \state_reg[1]  (.CP(CLK),
	.D(n_72),
	.Q(state[1]),
	.RN(n_97));
   HS65_GS_DFPRQX9 \state_reg[2]  (.CP(CLK),
	.D(n_73),
	.Q(state[2]),
	.RN(FE_OFN5_n_97));
   HS65_GS_NOR2X6 g2329_730256179 (.A(FE_OFN2_FE_OFN0_n_172),
	.B(n_75),
	.Z(n_76));
   HS65_GS_MUXI21X2 g2331_730256179 (.D0(\N_TRANSFER[3] ),
	.D1(n_70),
	.S0(n_88),
	.Z(n_75));
   HS65_GS_NOR2X6 g2334_730256179 (.A(FE_OFN2_FE_OFN0_n_172),
	.B(n_71),
	.Z(n_74));
   HS65_GS_NAND4ABX3 g2335_730256179 (.A(n_135),
	.B(n_42),
	.C(n_22),
	.D(n_63),
	.Z(n_73));
   HS65_GS_NAND3X5 g2336_730256179 (.A(n_60),
	.B(n_22),
	.C(n_64),
	.Z(n_72));
   HS65_GS_MUXI21X2 g2338_730256179 (.D0(\N_TRANSFER[2] ),
	.D1(n_68),
	.S0(n_88),
	.Z(n_71));
   HS65_GSS_XOR2X6 g2339_730256179 (.A(\N_TRANSFER[3] ),
	.B(n_67),
	.Z(n_70));
   HS65_GS_NAND2X7 g2341_730256179 (.A(n_60),
	.B(n_65),
	.Z(n_69));
   HS65_GS_HA1X4 g2342_730256179 (.A0(\N_TRANSFER[2] ),
	.B0(n_57),
	.CO(n_67),
	.S0(n_68));
   HS65_GS_NOR2X6 g2343_730256179 (.A(FE_OFN2_FE_OFN0_n_172),
	.B(n_61),
	.Z(n_66));
   HS65_GS_AOI212X4 g2344_730256179 (.A(n_7),
	.B(n_59),
	.C(n_11),
	.D(n_169),
	.E(n_42),
	.Z(n_65));
   HS65_GS_AOI312X4 g2345_730256179 (.A(n_6),
	.B(n_19),
	.C(n_315),
	.D(n_11),
	.E(n_170),
	.F(n_62),
	.Z(n_64));
   HS65_GS_AOI32X5 g2346_730256179 (.A(PIReqCNTL[7]),
	.B(PIReqCNTL[4]),
	.C(n_59),
	.D(n_9),
	.E(n_12),
	.Z(n_63));
   HS65_GS_AO22X9 g2349_730256179 (.A(n_20),
	.B(n_59),
	.C(n_10),
	.D(n_135),
	.Z(n_62));
   HS65_GS_MUXI21X2 g2350_730256179 (.D0(\N_TRANSFER[1] ),
	.D1(n_58),
	.S0(n_88),
	.Z(n_61));
   HS65_GS_HA1X4 g2385_730256179 (.A0(\N_TRANSFER[1] ),
	.B0(\N_TRANSFER[0] ),
	.CO(n_57),
	.S0(n_58));
   HS65_GS_AO222X4 g2386_730256179 (.A(FE_RN_1),
	.B(ADR_O[28]),
	.C(FE_OFN3_n_88),
	.D(Counter_Burst_Transfer_plus_69_28[28]),
	.E(PIReqADRS[28]),
	.F(FE_OFN2_FE_OFN0_n_172),
	.Z(n_56));
   HS65_GS_AO222X4 g2387_730256179 (.A(FE_RN_1),
	.B(ADR_O[29]),
	.C(FE_OFN3_n_88),
	.D(Counter_Burst_Transfer_plus_69_28[29]),
	.E(PIReqADRS[29]),
	.F(FE_OFN2_FE_OFN0_n_172),
	.Z(n_55));
   HS65_GS_AO22X9 g2388_730256179 (.A(ADR_O[1]),
	.B(n_15),
	.C(PIReqADRS[1]),
	.D(FE_OFN0_n_172),
	.Z(n_54));
   HS65_GS_AO22X9 g2389_730256179 (.A(ADR_O[0]),
	.B(n_15),
	.C(PIReqADRS[0]),
	.D(FE_OFN0_n_172),
	.Z(n_53));
   HS65_GS_AO222X4 g2390_730256179 (.A(STB_O),
	.B(ADR_O[21]),
	.C(n_88),
	.D(Counter_Burst_Transfer_plus_69_28[21]),
	.E(PIReqADRS[21]),
	.F(FE_OFN0_n_172),
	.Z(n_52));
   HS65_GS_AO222X4 g2391_730256179 (.A(FE_RN_1),
	.B(ADR_O[22]),
	.C(PIReqADRS[22]),
	.D(FE_OFN0_n_172),
	.E(FE_OFN3_n_88),
	.F(Counter_Burst_Transfer_plus_69_28[22]),
	.Z(n_51));
   HS65_GS_AO222X4 g2392_730256179 (.A(FE_RN_1),
	.B(ADR_O[23]),
	.C(FE_OFN3_n_88),
	.D(Counter_Burst_Transfer_plus_69_28[23]),
	.E(PIReqADRS[23]),
	.F(FE_OFN0_n_172),
	.Z(n_50));
   HS65_GS_AO222X4 g2393_730256179 (.A(FE_RN_1),
	.B(ADR_O[24]),
	.C(PIReqADRS[24]),
	.D(FE_OFN1_FE_OFN0_n_172),
	.E(FE_OFN3_n_88),
	.F(Counter_Burst_Transfer_plus_69_28[24]),
	.Z(n_49));
   HS65_GS_AO212X4 g2394_730256179 (.A(ADR_O[2]),
	.B(STB_O),
	.C(PIReqADRS[2]),
	.D(FE_OFN0_n_172),
	.E(n_17),
	.Z(n_48));
   HS65_GS_AO222X4 g2395_730256179 (.A(FE_RN_1),
	.B(ADR_O[25]),
	.C(FE_OFN3_n_88),
	.D(Counter_Burst_Transfer_plus_69_28[25]),
	.E(PIReqADRS[25]),
	.F(FE_OFN2_FE_OFN0_n_172),
	.Z(n_47));
   HS65_GS_AO222X4 g2396_730256179 (.A(FE_RN_1),
	.B(ADR_O[26]),
	.C(PIReqADRS[26]),
	.D(FE_OFN2_FE_OFN0_n_172),
	.E(FE_OFN3_n_88),
	.F(Counter_Burst_Transfer_plus_69_28[26]),
	.Z(n_46));
   HS65_GS_AO222X4 g2397_730256179 (.A(n_88),
	.B(Counter_Burst_Transfer_plus_69_28[3]),
	.C(ADR_O[3]),
	.D(STB_O),
	.E(PIReqADRS[3]),
	.F(FE_OFN1_FE_OFN0_n_172),
	.Z(n_45));
   HS65_GS_AO222X4 g2398_730256179 (.A(FE_RN_1),
	.B(ADR_O[27]),
	.C(FE_OFN3_n_88),
	.D(Counter_Burst_Transfer_plus_69_28[27]),
	.E(PIReqADRS[27]),
	.F(FE_OFN2_FE_OFN0_n_172),
	.Z(n_44));
   HS65_GS_NOR2X6 g2399_730256179 (.A(FE_OFN2_FE_OFN0_n_172),
	.B(n_21),
	.Z(n_43));
   HS65_GS_NAND4ABX3 g2402_730256179 (.A(state[2]),
	.B(n_10),
	.C(state[0]),
	.D(state[1]),
	.Z(n_60));
   HS65_GS_NOR3AX2 g2405_730256179 (.A(PIReqVALID),
	.B(ACK_I),
	.C(n_13),
	.Z(n_59));
   HS65_GS_AO222X4 g2406_730256179 (.A(FE_OFN1_FE_OFN0_n_172),
	.B(PIReqADRS[4]),
	.C(ADR_O[4]),
	.D(STB_O),
	.E(Counter_Burst_Transfer_plus_69_28[4]),
	.F(n_88),
	.Z(n_41));
   HS65_GS_AO222X4 g2407_730256179 (.A(FE_RN_1),
	.B(ADR_O[30]),
	.C(FE_OFN3_n_88),
	.D(Counter_Burst_Transfer_plus_69_28[30]),
	.E(PIReqADRS[30]),
	.F(FE_OFN2_FE_OFN0_n_172),
	.Z(n_40));
   HS65_GS_AO212X4 g2408_730256179 (.A(FE_OFN3_n_88),
	.B(Counter_Burst_Transfer_plus_69_28[31]),
	.C(ADR_O[31]),
	.D(FE_RN_1),
	.E(n_14),
	.Z(n_39));
   HS65_GS_AO222X4 g2409_730256179 (.A(Counter_Burst_Transfer_plus_69_28[6]),
	.B(n_88),
	.C(ADR_O[6]),
	.D(STB_O),
	.E(PIReqADRS[6]),
	.F(FE_OFN1_FE_OFN0_n_172),
	.Z(n_38));
   HS65_GS_AO222X4 g2410_730256179 (.A(n_88),
	.B(Counter_Burst_Transfer_plus_69_28[5]),
	.C(ADR_O[5]),
	.D(STB_O),
	.E(PIReqADRS[5]),
	.F(FE_OFN1_FE_OFN0_n_172),
	.Z(n_37));
   HS65_GS_AO222X4 g2411_730256179 (.A(FE_OFN1_FE_OFN0_n_172),
	.B(PIReqADRS[7]),
	.C(ADR_O[7]),
	.D(STB_O),
	.E(n_88),
	.F(Counter_Burst_Transfer_plus_69_28[7]),
	.Z(n_36));
   HS65_GS_AO222X4 g2412_730256179 (.A(STB_O),
	.B(ADR_O[8]),
	.C(n_88),
	.D(Counter_Burst_Transfer_plus_69_28[8]),
	.E(PIReqADRS[8]),
	.F(FE_OFN0_n_172),
	.Z(n_35));
   HS65_GS_AO222X4 g2413_730256179 (.A(STB_O),
	.B(ADR_O[9]),
	.C(n_88),
	.D(Counter_Burst_Transfer_plus_69_28[9]),
	.E(PIReqADRS[9]),
	.F(FE_OFN0_n_172),
	.Z(n_34));
   HS65_GS_AO222X4 g2414_730256179 (.A(STB_O),
	.B(ADR_O[10]),
	.C(n_88),
	.D(Counter_Burst_Transfer_plus_69_28[10]),
	.E(PIReqADRS[10]),
	.F(FE_OFN1_FE_OFN0_n_172),
	.Z(n_33));
   HS65_GS_AO222X4 g2415_730256179 (.A(STB_O),
	.B(ADR_O[20]),
	.C(n_88),
	.D(Counter_Burst_Transfer_plus_69_28[20]),
	.E(PIReqADRS[20]),
	.F(FE_OFN0_n_172),
	.Z(n_32));
   HS65_GS_AO222X4 g2416_730256179 (.A(STB_O),
	.B(ADR_O[11]),
	.C(n_88),
	.D(Counter_Burst_Transfer_plus_69_28[11]),
	.E(PIReqADRS[11]),
	.F(FE_OFN1_FE_OFN0_n_172),
	.Z(n_31));
   HS65_GS_AO222X4 g2417_730256179 (.A(FE_RN_1),
	.B(ADR_O[12]),
	.C(PIReqADRS[12]),
	.D(FE_OFN1_FE_OFN0_n_172),
	.E(FE_OFN3_n_88),
	.F(Counter_Burst_Transfer_plus_69_28[12]),
	.Z(n_30));
   HS65_GS_AO222X4 g2418_730256179 (.A(FE_RN_1),
	.B(ADR_O[13]),
	.C(PIReqADRS[13]),
	.D(FE_OFN1_FE_OFN0_n_172),
	.E(FE_OFN3_n_88),
	.F(Counter_Burst_Transfer_plus_69_28[13]),
	.Z(n_29));
   HS65_GS_AO222X4 g2419_730256179 (.A(FE_RN_1),
	.B(ADR_O[14]),
	.C(PIReqADRS[14]),
	.D(FE_OFN1_FE_OFN0_n_172),
	.E(FE_OFN3_n_88),
	.F(Counter_Burst_Transfer_plus_69_28[14]),
	.Z(n_28));
   HS65_GS_AO222X4 g2420_730256179 (.A(FE_RN_1),
	.B(ADR_O[15]),
	.C(FE_OFN3_n_88),
	.D(Counter_Burst_Transfer_plus_69_28[15]),
	.E(PIReqADRS[15]),
	.F(FE_OFN1_FE_OFN0_n_172),
	.Z(n_27));
   HS65_GS_AO222X4 g2421_730256179 (.A(FE_RN_1),
	.B(ADR_O[16]),
	.C(FE_OFN3_n_88),
	.D(Counter_Burst_Transfer_plus_69_28[16]),
	.E(PIReqADRS[16]),
	.F(FE_OFN1_FE_OFN0_n_172),
	.Z(n_26));
   HS65_GS_AO222X4 g2422_730256179 (.A(FE_RN_1),
	.B(ADR_O[17]),
	.C(FE_OFN3_n_88),
	.D(Counter_Burst_Transfer_plus_69_28[17]),
	.E(PIReqADRS[17]),
	.F(FE_OFN1_FE_OFN0_n_172),
	.Z(n_25));
   HS65_GS_AO222X4 g2423_730256179 (.A(FE_RN_1),
	.B(ADR_O[18]),
	.C(FE_OFN3_n_88),
	.D(Counter_Burst_Transfer_plus_69_28[18]),
	.E(PIReqADRS[18]),
	.F(FE_OFN1_FE_OFN0_n_172),
	.Z(n_24));
   HS65_GS_AO222X4 g2424_730256179 (.A(STB_O),
	.B(ADR_O[19]),
	.C(n_88),
	.D(Counter_Burst_Transfer_plus_69_28[19]),
	.E(PIReqADRS[19]),
	.F(FE_OFN1_FE_OFN0_n_172),
	.Z(n_23));
   HS65_GS_AO22X9 g2425_730256179 (.A(ACK_I),
	.B(n_19),
	.C(n_10),
	.D(n_170),
	.Z(n_42));
   HS65_GSS_XNOR2X6 g2429_730256179 (.A(\N_TRANSFER[0] ),
	.B(n_88),
	.Z(n_21));
   HS65_GSS_XOR2X3 g2430_730256179 (.A(PIReqCNTL[4]),
	.B(PIReqCNTL[7]),
	.Z(n_20));
   HS65_GS_NAND2X7 g2431_730256179 (.A(ACK_I),
	.B(n_12),
	.Z(n_22));
   HS65_GS_OR2X4 g2432_730256179 (.A(PIReqCNTL[2]),
	.B(PIReqCNTL[1]),
	.Z(n_18));
   HS65_GS_NOR2X6 g2433_730256179 (.A(ADR_O[2]),
	.B(FE_DBTN0_n_88),
	.Z(n_17));
   HS65_GS_OR2X9 g2435_730256179 (.A(\TOT_TRANSFER_O[0] ),
	.B(FE_OFN2_FE_OFN0_n_172),
	.Z(n_16));
   HS65_GS_NOR2AX3 g2436_730256179 (.A(n_171),
	.B(state[1]),
	.Z(n_19));
   HS65_GS_IVX7 g2437_730256179 (.A(n_13),
	.Z(n_14));
   HS65_GS_IVX9 g2438_730256179 (.A(n_11),
	.Z(n_10));
   HS65_GS_NAND2AX7 g2439_730256179 (.A(n_315),
	.B(PIReqCNTL[0]),
	.Z(n_9));
   HS65_GS_AND2X4 g2440_730256179 (.A(PIReqCNTL[1]),
	.B(PIReqCNTL[2]),
	.Z(n_8));
   HS65_GS_NAND2X7 g2441_730256179 (.A(FE_DBTN0_n_88),
	.B(n_4),
	.Z(n_15));
   HS65_GS_NAND2X7 g2442_730256179 (.A(PIReqADRS[31]),
	.B(FE_OFN2_FE_OFN0_n_172),
	.Z(n_13));
   HS65_GS_NOR2AX3 g2443_730256179 (.A(n_136),
	.B(state[0]),
	.Z(n_12));
   HS65_GS_NAND2X2 g2444_730256179 (.A(ACK_I),
	.B(PIRespRDY),
	.Z(n_11));
   HS65_GS_IVX9 g2448_730256179 (.A(PIReqCNTL[4]),
	.Z(n_7));
   HS65_GS_IVX9 g2456_730256179 (.A(ACK_I),
	.Z(n_6));
   HS65_GS_IVX9 drc_bufs2471_730256179 (.A(STB_O),
	.Z(n_4));
   HS65_GSS_XOR2X6 Counter_Burst_Transfer_add_69_28_g917_730256179 (.A(ADR_O[31]),
	.B(Counter_Burst_Transfer_add_69_28_n_635),
	.Z(Counter_Burst_Transfer_plus_69_28[31]));
   HS65_GS_HA1X4 Counter_Burst_Transfer_add_69_28_g918_730256179 (.A0(ADR_O[30]),
	.B0(Counter_Burst_Transfer_add_69_28_n_637),
	.CO(Counter_Burst_Transfer_add_69_28_n_635),
	.S0(Counter_Burst_Transfer_plus_69_28[30]));
   HS65_GS_HA1X4 Counter_Burst_Transfer_add_69_28_g919_730256179 (.A0(ADR_O[29]),
	.B0(Counter_Burst_Transfer_add_69_28_n_639),
	.CO(Counter_Burst_Transfer_add_69_28_n_637),
	.S0(Counter_Burst_Transfer_plus_69_28[29]));
   HS65_GS_HA1X4 Counter_Burst_Transfer_add_69_28_g920_730256179 (.A0(ADR_O[28]),
	.B0(Counter_Burst_Transfer_add_69_28_n_641),
	.CO(Counter_Burst_Transfer_add_69_28_n_639),
	.S0(Counter_Burst_Transfer_plus_69_28[28]));
   HS65_GS_HA1X4 Counter_Burst_Transfer_add_69_28_g921_730256179 (.A0(ADR_O[27]),
	.B0(Counter_Burst_Transfer_add_69_28_n_643),
	.CO(Counter_Burst_Transfer_add_69_28_n_641),
	.S0(Counter_Burst_Transfer_plus_69_28[27]));
   HS65_GS_HA1X4 Counter_Burst_Transfer_add_69_28_g922_730256179 (.A0(ADR_O[26]),
	.B0(Counter_Burst_Transfer_add_69_28_n_645),
	.CO(Counter_Burst_Transfer_add_69_28_n_643),
	.S0(Counter_Burst_Transfer_plus_69_28[26]));
   HS65_GS_HA1X4 Counter_Burst_Transfer_add_69_28_g923_730256179 (.A0(ADR_O[25]),
	.B0(Counter_Burst_Transfer_add_69_28_n_647),
	.CO(Counter_Burst_Transfer_add_69_28_n_645),
	.S0(Counter_Burst_Transfer_plus_69_28[25]));
   HS65_GS_HA1X4 Counter_Burst_Transfer_add_69_28_g924_730256179 (.A0(ADR_O[24]),
	.B0(Counter_Burst_Transfer_add_69_28_n_649),
	.CO(Counter_Burst_Transfer_add_69_28_n_647),
	.S0(Counter_Burst_Transfer_plus_69_28[24]));
   HS65_GS_HA1X4 Counter_Burst_Transfer_add_69_28_g925_730256179 (.A0(ADR_O[23]),
	.B0(Counter_Burst_Transfer_add_69_28_n_651),
	.CO(Counter_Burst_Transfer_add_69_28_n_649),
	.S0(Counter_Burst_Transfer_plus_69_28[23]));
   HS65_GS_HA1X4 Counter_Burst_Transfer_add_69_28_g926_730256179 (.A0(ADR_O[22]),
	.B0(Counter_Burst_Transfer_add_69_28_n_653),
	.CO(Counter_Burst_Transfer_add_69_28_n_651),
	.S0(Counter_Burst_Transfer_plus_69_28[22]));
   HS65_GS_HA1X4 Counter_Burst_Transfer_add_69_28_g927_730256179 (.A0(ADR_O[21]),
	.B0(Counter_Burst_Transfer_add_69_28_n_655),
	.CO(Counter_Burst_Transfer_add_69_28_n_653),
	.S0(Counter_Burst_Transfer_plus_69_28[21]));
   HS65_GS_HA1X4 Counter_Burst_Transfer_add_69_28_g928_730256179 (.A0(ADR_O[20]),
	.B0(Counter_Burst_Transfer_add_69_28_n_657),
	.CO(Counter_Burst_Transfer_add_69_28_n_655),
	.S0(Counter_Burst_Transfer_plus_69_28[20]));
   HS65_GS_HA1X4 Counter_Burst_Transfer_add_69_28_g929_730256179 (.A0(ADR_O[19]),
	.B0(Counter_Burst_Transfer_add_69_28_n_659),
	.CO(Counter_Burst_Transfer_add_69_28_n_657),
	.S0(Counter_Burst_Transfer_plus_69_28[19]));
   HS65_GS_HA1X4 Counter_Burst_Transfer_add_69_28_g930_730256179 (.A0(ADR_O[18]),
	.B0(Counter_Burst_Transfer_add_69_28_n_661),
	.CO(Counter_Burst_Transfer_add_69_28_n_659),
	.S0(Counter_Burst_Transfer_plus_69_28[18]));
   HS65_GS_HA1X4 Counter_Burst_Transfer_add_69_28_g931_730256179 (.A0(ADR_O[17]),
	.B0(Counter_Burst_Transfer_add_69_28_n_663),
	.CO(Counter_Burst_Transfer_add_69_28_n_661),
	.S0(Counter_Burst_Transfer_plus_69_28[17]));
   HS65_GS_HA1X4 Counter_Burst_Transfer_add_69_28_g932_730256179 (.A0(ADR_O[16]),
	.B0(Counter_Burst_Transfer_add_69_28_n_665),
	.CO(Counter_Burst_Transfer_add_69_28_n_663),
	.S0(Counter_Burst_Transfer_plus_69_28[16]));
   HS65_GS_HA1X4 Counter_Burst_Transfer_add_69_28_g933_730256179 (.A0(ADR_O[15]),
	.B0(Counter_Burst_Transfer_add_69_28_n_667),
	.CO(Counter_Burst_Transfer_add_69_28_n_665),
	.S0(Counter_Burst_Transfer_plus_69_28[15]));
   HS65_GS_HA1X4 Counter_Burst_Transfer_add_69_28_g934_730256179 (.A0(ADR_O[14]),
	.B0(Counter_Burst_Transfer_add_69_28_n_669),
	.CO(Counter_Burst_Transfer_add_69_28_n_667),
	.S0(Counter_Burst_Transfer_plus_69_28[14]));
   HS65_GS_HA1X4 Counter_Burst_Transfer_add_69_28_g935_730256179 (.A0(ADR_O[13]),
	.B0(Counter_Burst_Transfer_add_69_28_n_671),
	.CO(Counter_Burst_Transfer_add_69_28_n_669),
	.S0(Counter_Burst_Transfer_plus_69_28[13]));
   HS65_GS_HA1X4 Counter_Burst_Transfer_add_69_28_g936_730256179 (.A0(ADR_O[12]),
	.B0(Counter_Burst_Transfer_add_69_28_n_673),
	.CO(Counter_Burst_Transfer_add_69_28_n_671),
	.S0(Counter_Burst_Transfer_plus_69_28[12]));
   HS65_GS_HA1X4 Counter_Burst_Transfer_add_69_28_g937_730256179 (.A0(ADR_O[11]),
	.B0(Counter_Burst_Transfer_add_69_28_n_675),
	.CO(Counter_Burst_Transfer_add_69_28_n_673),
	.S0(Counter_Burst_Transfer_plus_69_28[11]));
   HS65_GS_HA1X4 Counter_Burst_Transfer_add_69_28_g938_730256179 (.A0(ADR_O[10]),
	.B0(Counter_Burst_Transfer_add_69_28_n_677),
	.CO(Counter_Burst_Transfer_add_69_28_n_675),
	.S0(Counter_Burst_Transfer_plus_69_28[10]));
   HS65_GS_HA1X4 Counter_Burst_Transfer_add_69_28_g939_730256179 (.A0(ADR_O[9]),
	.B0(Counter_Burst_Transfer_add_69_28_n_679),
	.CO(Counter_Burst_Transfer_add_69_28_n_677),
	.S0(Counter_Burst_Transfer_plus_69_28[9]));
   HS65_GS_HA1X4 Counter_Burst_Transfer_add_69_28_g940_730256179 (.A0(ADR_O[8]),
	.B0(Counter_Burst_Transfer_add_69_28_n_681),
	.CO(Counter_Burst_Transfer_add_69_28_n_679),
	.S0(Counter_Burst_Transfer_plus_69_28[8]));
   HS65_GS_HA1X4 Counter_Burst_Transfer_add_69_28_g941_730256179 (.A0(ADR_O[7]),
	.B0(Counter_Burst_Transfer_add_69_28_n_683),
	.CO(Counter_Burst_Transfer_add_69_28_n_681),
	.S0(Counter_Burst_Transfer_plus_69_28[7]));
   HS65_GS_HA1X4 Counter_Burst_Transfer_add_69_28_g942_730256179 (.A0(ADR_O[6]),
	.B0(Counter_Burst_Transfer_add_69_28_n_685),
	.CO(Counter_Burst_Transfer_add_69_28_n_683),
	.S0(Counter_Burst_Transfer_plus_69_28[6]));
   HS65_GS_HA1X4 Counter_Burst_Transfer_add_69_28_g943_730256179 (.A0(ADR_O[5]),
	.B0(Counter_Burst_Transfer_add_69_28_n_687),
	.CO(Counter_Burst_Transfer_add_69_28_n_685),
	.S0(Counter_Burst_Transfer_plus_69_28[5]));
   HS65_GS_HA1X4 Counter_Burst_Transfer_add_69_28_g944_730256179 (.A0(ADR_O[4]),
	.B0(Counter_Burst_Transfer_add_69_28_n_689),
	.CO(Counter_Burst_Transfer_add_69_28_n_687),
	.S0(Counter_Burst_Transfer_plus_69_28[4]));
   HS65_GS_HA1X4 Counter_Burst_Transfer_add_69_28_g945_730256179 (.A0(ADR_O[3]),
	.B0(ADR_O[2]),
	.CO(Counter_Burst_Transfer_add_69_28_n_689),
	.S0(Counter_Burst_Transfer_plus_69_28[3]));
endmodule

