# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">= 1.9.5"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_check_update = false
  config.vbguest.auto_update = false
  config.vm.define "ubuntu" do |vb|
    config.vm.provider "virtualbox" do |vb|
      vb.name = "ubuntu"
      vb.memory = "2048"
      vb.cpus = 2
    end
    vb.vm.hostname = "ubuntu"
    vb.vm.network "private_network", ip: "192.168.255.254", virtualbox__intnet: true
    vb.vm.provision "shell", inline: <<-SHELL
      cd $HOME
      apt-get update
      apt-get install -y vim tmux git xorg core-network-*
      apt-get install -yf
      /etc/init.d/core-daemon start
    SHELL
  end
end
